conversation/urls.py
from django.urls import path

from . import views

app_name = "conversation"

urlpatterns = [
    path("", views.inbox, name="inbox"),
    path("<int:id>/<slug:slug>/", views.detail, name="detail"),
    path("new/<int:item_pk>/<slug:slug>/", views.new_conversation, name="new"),
]

item/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("add/", views.add_item, name="add_item"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("<int:id>/delete/", views.delete, name="delete"),
    path("<int:id>/<slug:slug>/edit/", views.edit_item, name="edit"),
    path("browse/", views.browse, name="browse"),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("inbox/", include("conversation.urls")),
    path("item/", include("item.urls")),
    path("", include("shop.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm


urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(authentication_form=LoginForm),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("", views.index, name="index"),
    path("<slug:category_slug>/", views.index, name="items_by_category"),
    path("<int:id>/<slug:slug>/", views.item_detail, name="detail"),
]

item/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    def get_absolute_url(self):
        return reverse("items_by_category", args=[self.slug])

    class Meta:
        ordering = ["name"]
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self) -> str:
        return self.name


class Item(models.Model):
    category = models.ForeignKey(
        Category, related_name="items", on_delete=models.CASCADE
    )
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    is_sold = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to="item_images/%Y/%m/%d", blank=True, null=True)
    created_by = models.ForeignKey(User, related_name="items", on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse("detail", args=[self.id, self.slug])

    class Meta:
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["id", "slug"]),
            models.Index(fields=["name"]),
            models.Index(fields=["created_at"]),
        ]

    def __str__(self) -> str:
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

shop/models.py
from django.db import models

# Create your models here.

item/forms.py
from django import forms
from django.core.files.base import ContentFile
from django.utils.text import slugify
import requests

from .models import Item

INPUT_CLASSES = "w-full py-4 px-6 rounded-xl border"


class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = (
            "category",
            "name",
            "description",
            "price",
            "image",
        )
        widgets = {
            "category": forms.Select(attrs={"class": INPUT_CLASSES}),
            "name": forms.TextInput(attrs={"class": INPUT_CLASSES}),
            "description": forms.Textarea(attrs={"class": INPUT_CLASSES}),
            "price": forms.TextInput(attrs={"class": INPUT_CLASSES}),
            "image": forms.FileInput(attrs={"class": INPUT_CLASSES}),
        }


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = (
            "name",
            "description",
            "price",
            "image",
            "is_sold",
        )
        widgets = {
            "name": forms.TextInput(attrs={"class": INPUT_CLASSES}),
            "description": forms.Textarea(attrs={"class": INPUT_CLASSES}),
            "price": forms.TextInput(attrs={"class": INPUT_CLASSES}),
            "image": forms.FileInput(attrs={"class": INPUT_CLASSES}),
        }

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Your username",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )
    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Your email adress",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Enter password",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Repeat password",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Your username",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Enter password",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )

item/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from .models import Item, Category
from .forms import NewItemForm, EditItemForm


@login_required
def add_item(request):
    if request.method == "POST":
        form = NewItemForm(request.POST, request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()
            return redirect("detail", id=item.id, slug=item.slug)
    else:
        form = NewItemForm()
    return render(request, "item/add_item.html", {"form": form})


@login_required
def dashboard(request):
    items = Item.objects.filter(created_by=request.user)
    categories = Category.objects.all()

    return render(
        request, "item/dashboard.html", {"items": items, "categories": categories}
    )


@login_required
def delete(request, id):
    item = get_object_or_404(Item, id=id, created_by=request.user)
    item.delete()

    return redirect("dashboard")


@login_required
def edit_item(request, id, slug):
    item = get_object_or_404(Item, id=id, slug=slug, created_by=request.user)
    if request.method == "POST":
        form = EditItemForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()
            return redirect("detail", id=item.id, slug=item.slug)
    else:
        form = EditItemForm(instance=item)
    return render(request, "item/add_item.html", {"form": form})


def browse(request):
    query = request.GET.get("query", "")
    # category_slug = request.GET.get("category", "")
    category_id = request.GET.get("category", 0)
    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)

    if category_id:
        items = items.filter(
            category_id=category_id,
        )

    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))

    return render(
        request,
        "item/browse.html",
        {
            "items": items,
            "query": query,
            "categories": categories,
            # "category_slug": category_slug,
            "category_id": int(category_id),
        },
    )

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy

from item.models import Category, Item
from .forms import SignUpForm


def index(request, category_slug=None):
    category = None
    items = Item.objects.filter(is_sold=False)
    categories = Category.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        items = items.filter(category=category)
    return render(
        request,
        "shop/item/index.html",
        {"items": items, "categories": categories, "category": category},
    )


def item_detail(request, id, slug):
    item = get_object_or_404(Item, id=id, slug=slug, is_sold=False)
    categories = Category.objects.all()
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(
        id=id
    )[0:3]
    return render(
        request,
        "shop/item/detail.html",
        {"item": item, "categories": categories, "related_items": related_items},
    )


def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
    else:
        form = SignUpForm()
    return render(request, "registration/signup.html", {"form": form})

shop/templates/shop/item/detail.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}{{ item.name }}{% endblock title %}

{% block content %}

<div class="grid grid-cols-5 gap-6">
         <div class="col-span-2">
            <img src="{% if item.image %}{{ item.image.url }}{% else %}
            {% static 'img/no_image.png' %}{% endif %}"class="rounded-t-[0.625rem] h-[400px] rounded-b-none w-full">                        
        </div>                  
            
        <div class="col-span-3 p-6 bg-gray-100 rounded-xl">
            <h2 class="text-2xl">{{ item.name }}</h2>
            <p class="text-gray-500"><strong>Price: </strong>{{ item.price }}</p>
            <p class="text-gray-500"><strong>Seller: </strong>{{ item.created_by.username }}</p>
        
        {% if item.description %}
            <p class="text-gray-700">
                <strong class="text-gray-500">Description:</strong><br>
                {{ item.description }}
            </p>
        {% endif %}
        
        {% if request.user == item.created_by %}
            <div class="mt-6 p-6 bg-white rounded-xl">
                <p>This is your item!</p>
                
                <a href="{% url 'edit' item.id item.slug %}" class="inline-block 
                mt-6 px-6 py-3 text-lg font-semibold 
                bg-teal-500 text-white rounded-xl">Edit</a>
                <a href="{% url 'delete' item.id %}" class="inline-block 
                mt-6 px-6 py-3 text-lg font-semibold 
                bg-red-500 text-white rounded-xl">Delete</a>
            </div>
            {% else %} 
            <a href="{% url 'conversation:new' item.id item.slug %}" class="inline-block mt-6 px-6 py-3 text-lg 
            font-semibold bg-teal-500 text-white rounded-xl 
            hover:bg-teal-700">Contact seller</a>
            {% endif %} 
        </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Related items</h2>
    
    <div class="grid grid-cols-3 gap-3">
        {% for item in related_items %}
          <div>
            <a href="{{ item.get_absolute_url }}">
                
                <div class="image">
                    <img src="{% if item.image %}{{ item.image.url }}{% else %}
                    {% static 'img/no_image.png' %}{% endif %}"class="rounded-t-[0.625rem] h-[400px] rounded-b-none w-full">                        
                </div>                  
                
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{ item.name }}</h2>
                    <p class="text-gray-500">Price: {{ item.price }}</p>
                </div>
            </a>
          </div>
        {% endfor %}  
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Categories</h2>
    
    <div class="grid grid-cols-3 gap-3">
        {% for category in categories %}             
        <div>
            {% if category.slug == category.slug %}{% endif %}
            <a href="{{ category.get_absolute_url }}">                
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{ category.name }}</h2>
                    <p class="text-gray-500">{{ category.items.count }}item{{ category.items.count|pluralize }}</p>
                </div>
            </a>
          </div>
        {% endfor %}
    </div>
</div>



{% endblock content %}

shop/templates/shop/item/index.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}{% if category %}{{ category.name }}{% else %}Welcome{% endif %}{% endblock title %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest items</h2>
        
        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
              <div>
                <a href="{{ item.get_absolute_url }}">
                    
                    <div class="image">
                        <img src="{% if item.image %}{{ item.image.url }}{% else %}
                        {% static 'img/no_image.png' %}{% endif %}"class="rounded-t-[0.625rem] h-[400px] rounded-b-none w-full">                        
                    </div>                  
                    
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ item.name }}</h2>
                        <p class="text-gray-500">Price: {{ item.price }}</p>
                    </div>
                </a>
              </div>
            {% endfor %}  
        </div>
    </div>
    
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>
        
        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}             
            <div>
                {% if category.slug == category.slug %}{% endif %}
                <a href="{{ category.get_absolute_url }}">                
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ category.name }}</h2>
                        <p class="text-gray-500">{{ category.items.count }}item{{ category.items.count|pluralize }}</p>
                    </div>
                </a>
              </div>
            {% endfor %}
        </div>
    </div>    
{% endblock content %}