conversation/urls.py
from django.urls import path

from . import views

app_name = "conversation"

urlpatterns = [
    path("", views.inbox, name="inbox"),
    path("<int:id>/<slug:slug>/", views.detail, name="detail"),
    path("new/<int:item_pk>/<slug:slug>/", views.new_conversation, name="new"),
]

item/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("add/", views.add_item, name="add_item"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("<int:id>/delete/", views.delete, name="delete"),
    path("<int:id>/<slug:slug>/edit/", views.edit_item, name="edit"),
    path("browse/", views.browse, name="browse"),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("inbox/", include("conversation.urls")),
    path("item/", include("item.urls")),
    path("", include("shop.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm


urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(authentication_form=LoginForm),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("", views.index, name="index"),
    path("<slug:category_slug>/", views.index, name="items_by_category"),
    path("<int:id>/<slug:slug>/", views.item_detail, name="detail"),
]

shop/models.py
from django.db import models

# Create your models here.

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Your username",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )
    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Your email adress",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Enter password",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Repeat password",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Your username",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Enter password",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy

from item.models import Category, Item
from .forms import SignUpForm


def index(request, category_slug=None):
    category = None
    items = Item.objects.filter(is_sold=False)
    categories = Category.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        items = items.filter(category=category)
    return render(
        request,
        "shop/item/index.html",
        {"items": items, "categories": categories, "category": category},
    )


def item_detail(request, id, slug):
    item = get_object_or_404(Item, id=id, slug=slug, is_sold=False)
    categories = Category.objects.all()
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(
        id=id
    )[0:3]
    return render(
        request,
        "shop/item/detail.html",
        {"item": item, "categories": categories, "related_items": related_items},
    )


def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
    else:
        form = SignUpForm()
    return render(request, "registration/signup.html", {"form": form})

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %} | My shop</title>
    <script src="https://cdn.tailwindcss.com"></script>
   
</head>
<body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-semibold">Home</a>
        
        <div class="space-x-6">
            {% if request.user.is_authenticated %}
            <a href="{% url 'add_item' %}" class="text-lg font-semibold hover:text-gray-500">New item</a>
            <a href="{% url 'browse' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>
            <a href="#" class="text-lg font-bold">Hello, {{ user.username }}</a>
            <a href="{% url 'logout' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white 
            rounded-xl hover:bg-gray-700">Log out</a>
            
            
            <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white 
            rounded-xl hover:bg-teal-700">Inbox</a>
            <a href="{% url 'dashboard' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white 
            rounded-xl hover:bg-gray-700">Dashboard</a>
            {% else %}
            <a href="{% url 'signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white 
            rounded-xl hover:bg-teal-700">Sign up</a>
            <a href="{% url 'login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white 
            rounded-xl hover:bg-gray-700">Log in</a>
            {% endif %}
        </div>
    </nav>
    <div class="py-6 px-6">
        {% block content %}
        {% endblock content %}
    </div>
    
    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>
            
            <p class="text-lg text-gray-500">Lorem ipsum. This is a footer. Focus on getting better! Lorem ipsum. This is a footer. Focus on getting better!</p>
        </div>
        
        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
            <ul class="space-y-2">
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li>
            </ul>
        </div>
    </footer>
</body>
</html>